config/routes.rb
Rails.application.routes.draw do
  resources :collections do
    resources :items
  end

  root 'home#index'
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :collection
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item

  # GET /items
  # GET /items.json
  def index
    @items = @collection.items.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = @collection.items.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = @collection.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to [@collection, @item], notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to [@collection, @item], notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @collection = Collection.find(params[:collection_id])
      @item = @collection.items.find(params[:id]) if params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(controller)
    return 'active' if controller == 'collections' && controller_name == 'items'

    controller == controller_name ? 'active' : ''
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
  def cataloged_items(collection)
    collection.items.size
  end

  def acquired_items(collection)
    collection.items.where('amount > 0').size
  end

  def missing_items(collection)
    collection.items.where('amount <= 0').size
  end

  def percentage_acquired(collection)
    (acquired_items(collection).to_f/cataloged_items(collection).to_f)*100
  end

  def percentage_missing(collection)
    (missing_items(collection).to_f/cataloged_items(collection).to_f)*100
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-sm-4">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name, placeholder: 'Informe o nome da coleção', class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit value, class: 'btn btn-success', data: { disable_with: 'Aguarde...' } %>
    <%= link_to 'Voltar', collections_path, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Alteração de coleção</h1>

<%= render partial: "form", locals: { value: 'Atualizar coleção' } %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li class="active">Listagem de Coleções</li>
</ol>

<h1>Listagem de coleções</h1>

<table class="table table-bordered table-hover table-collections">
  <thead>
    <tr>
      <th>Nome</th>
      <th class="amount">Itens catalogados</th>
      <th class="amount">Itens adquiridos</th>
      <th class="amount">Itens faltantes</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= link_to collection.name, collection %></td>
        <td><%= cataloged_items(collection) %></td>
        <td><%= acquired_items(collection) %></td>
        <td><%= missing_items(collection) %></td>
        <td>
          <%= link_to fa_icon('eye'), collection %>
          <%= link_to fa_icon('edit'), edit_collection_path(collection) %>
          <%= link_to fa_icon('times'), collection, method: :delete, data: { confirm: 'Você deseja realmente excluir esta coleção?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova coleção', new_collection_path, class: 'btn btn-success' %>

app/views/collections/new.html.erb
<h1>Cadastro de coleção</h1>

<%= render partial: "form", locals: { value: 'Cadastrar coleção' } %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li><%= link_to 'Listagem de Coleções', collections_path %></li>
  <li class="active"><%= @collection.name %></li>
</ol>

<h1><%= @collection.name %></h1>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-body detail">
        <h2><%= @collection.name %></h2>
        <hr>
        <p><strong>Itens catalogados:</strong><%= cataloged_items(@collection) %></p>
        <hr>
        <p><strong>Itens adquiridos:</strong><%= acquired_items(@collection) %></p>
        <hr>
        <p><strong>Itens faltantes:</strong><%= missing_items(@collection) %></p>
     </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-body detail">
        <div id="container" style="min-width: 310px; height: 415px; max-width: 600px; margin: 0 auto"></div>
      </div>
    </div>
  </div>

  </div>

<p>
  <strong>Nome:</strong>
  <%= @collection.name %>
</p>
<p>
  <strong>Itens:</strong>
  <%= link_to 'Visualizar', collection_items_path(@collection) %>
</p>

<div class="actions">
  <%= link_to 'Editar coleção', edit_collection_path(@collection), class: 'btn btn-primary' %>
  <%= link_to 'Voltar', collections_path, class: 'btn btn-link' %>
</div>

<script>
$(function () {
  $('#container').highcharts({
    chart: {
      plotBackgroundColor: null,
      plotBorderWidth: 0,
      plotShadow: false
    },
    title: false,
    tooltip: {
      pointFormat: '<b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
      pie: {
        dataLabels: {
          enabled: true,
          distance: -50,
          style: {
            fontWeight: 'normal',
            fontSize: '13px',
            color: 'white',
            textShadow: '0px 1px 2px black'
          }
        },
        startAngle: -90,
        endAngle: 90,
        center: ['50%', '75%']
      }
    },
    series: [{
      type: 'pie',
      name: 'Itens',
      innerSize: '50%',
      data: [['Adquirido', <%= percentage_acquired(@collection) %>], ['Faltante', <%= percentage_missing(@collection) %>]]
    }],
    credits: {
     enabled: false
    }
  });
});
</script>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Collections</h1>
  <p class="lead">Sistema para cadastro e gerenciamento de itens colecionáveis</p>
  <p><%= link_to 'Cadastre sua primeira coleção', new_collection_path, class: 'btn btn-lg btn-success', role: "button" %></p>
</div>

<div class="row">
  <div class="col-lg-4">
    <h2>Simples e intuitivo</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  </div>
  <div class="col-lg-4">
    <h2>Gratuito</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
 </div>
  <div class="col-lg-4">
    <h2>Completo</h2>
    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_for([@collection, @item]) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-sm-4">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name, placeholder: 'Nome do item', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :amount, 'Quantidade' %>
      <%= f.number_field :amount, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit value, class: 'btn btn-success', data: { disable_with: 'Aguarde...' } %>
    <%= link_to 'Voltar', collection_items_path, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Alteração de item</h1>

<%= render partial: "form", locals: { value: 'Atualizar item' } %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li><%= link_to 'Listagem de Coleções', collections_path %></li>
  <li><%= link_to @collection.name, @collection %></li>
  <li class="active">Listagem de items</li>
</ol>

<h1>Listagem de items</h1>

<table class="table table-bordered table-hover table-collections">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Quantidade</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.name, [@collection, item] %></td>
        <td><%= item.amount %></td>
        <td>
          <%= link_to fa_icon('eye'), [@collection, item] %>
          <%= link_to fa_icon('edit'), edit_collection_item_path(@collection, item) %>
          <%= link_to fa_icon('times'), [@collection, item], method: :delete, data: { confirm: 'Você deseja realmente excluir este item?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo item', new_collection_item_path(@collection), class: 'btn btn-success' %>

app/views/items/new.html.erb
<h1>Cadastro de item</h1>

<%= render partial: "form", locals: { value: 'Cadastrar item' } %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li><%= link_to 'Listagem de Coleções', collections_path %></li>
  <li><%= link_to @collection.name, @collection %></li>
  <li><%= link_to 'Listagem de items', collection_items_path(@collection) %></li>
  <li class="active"><%= @item.name %></li>
</ol>

<h1><%= @item.name %></h1>

<p>
  <strong>Nome:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @item.amount %>
</p>

<div class="actions">
  <%= link_to 'Editar item', edit_collection_item_path(@collection, @item), class: 'btn btn-primary' %>
  <%= link_to 'Voltar', collection_items_path(@collection), class: 'btn btn-link' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Sistema para cadastro e gerenciamento de itens colecionáveis">
    <meta name="author" content="">

    <title>Collections</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">
      <div class="masthead">
        <nav>
          <ul class="nav nav-justified">
            <li class="<%= is_active?('home') %>"><%= link_to 'Página Inicial', root_path %></li>
            <li class="<%= is_active?('collections') %>"><%= link_to 'Coleções', collections_path %></li>
            <li><a href="#">Sobre</a></li>
            <li><a href="#">Contato</a></li>
          </ul>
        </nav>
      </div>

      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>

      <footer class="footer">
        <p>© 2015 Collections. Todos os direitos reservados</p>
      </footer>
    </div>
  </body>
</html>